Show an error if the command fails to spawn
Before, bacon showed no output at all if spawning failed. Now, it gives a useful error instead:
```
Error: error in computation for job 'run'

Caused by:
    0: failed to spawn cd "../example" && CARGO_TERM_COLOR="always" RUST_BACKTRACE="0" "./run.sh"
    1: Exec format error (os error 8)
```

To test this, you can create a bacon.toml with `jobs.run.command = ["/not/here"]` and execute `bacon run`.