Enable sha1 feature to gix
The new version of gix requires to either enable the sha1 or sha256 feature
flags. The default is sha1, but we disable the default features. Enable it.

```
error: Please set either the `sha1` or the `sha256` feature flag
  --> /home/puercopop/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/gix-hash-0.26.0/src/lib.rs:32:1
   |
32 | compile_error!("Please set either the `sha1` or the `sha256` feature flag");
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
``