Update gix version
The version of the indirect dependency gix-date has a security advisory open
against it. See https://rustsec.org/advisories/RUSTSEC-2025-0140. Update to the
latest gix version so that we depend on version of gix-date that doesn't have
any advisory open against it.

```
$ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 1190 security advisories (from /home/puercopop/.cargo/advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (380 crate dependencies)
Crate:     gix-date
Version:   0.10.5
Title:     Non-utf8 String can be created with `TimeBuf::as_str`
Date:      2025-12-29
ID:        RUSTSEC-2025-0140
URL:       https://rustsec.org/advisories/RUSTSEC-2025-0140
Solution:  Upgrade to >=0.12.0
[...]
error: 1 vulnerability found!
warning: 1 allowed warning found
```